routes/web.php
<?php

use App\Models\Equipment_key;
use App\Http\Controllers\Equipment_keyController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
	return view('auth/login');
}); // quando nao está logado

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'ProfileController@edit');
}); // esta rota é para quando o utilizador está logado e volta a entrar no ./ do site , para nao partir

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home')->middleware('auth'); // esta rota direciona para a Dashboard com os gráficos bonitos
Route::get('/home', 'ProfileController@edit')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('icons', ['as' => 'pages.icons', 'uses' => 'PageController@icons']);
	Route::get('maps', ['as' => 'pages.maps', 'uses' => 'PageController@maps']);
	Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'PageController@notifications']);
	Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'PageController@rtl']);
	Route::get('tables', ['as' => 'pages.tables', 'uses' => 'PageController@tables']);
	Route::get('typography', ['as' => 'pages.typography', 'uses' => 'PageController@typography']);
	Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'PageController@upgrade']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});




/* VISTAS E RESPETIVOS MÉTODOS  */
Route::group(['middleware' => 'auth'], function () {
	Route::get('attributes', ['as' => 'pages.attributes', 'uses' => 'Attributes1Controller@index']);

	Route::get('resaleCustomers', ['as' => 'pages.resaleCustomers', 'uses' => 'Resale_customerController@index']);
	Route::get('resaleCustomers/edit/{id}', 'Resale_customerController@getCustomerInfo');
	Route::post('resaleCustomers/create', 'Resale_customerController@create');
	Route::post('resaleCustomers/edit/{id}/update', 'Resale_customerController@update');
	Route::delete('resaleCustomers/delete/{id}', 'Resale_customerController@deleteCustomerResale');
	Route::get('resaleCustomers/filterToCSV', 'Resale_customerController@getFilteredQueryResults');
	Route::get('resaleCustomers/filterToCSV/download', 'Resale_customerController@getDownload');

	Route::get('segmentedCustomers', ['as' => 'pages.segmentedCustomers', 'uses' => 'Segmented_customerController@index']);
	Route::get('segmentedCustomers/edit/{id}', 'Segmented_customerController@getCustomerInfo');
	Route::post('segmentedCustomers/create', 'Segmented_customerController@create');
	Route::post('segmentedCustomers/edit/{id}/update', 'Segmented_customerController@update');
	Route::delete('segmentedCustomers/delete/{id}', 'Segmented_customerController@deleteCustomerSegmented');
	Route::get('segmentedCustomers/filterToCSV', 'Segmented_customerController@getFilteredQueryResults');
	Route::get('segmentedCustomers/filterToCSV/download', 'Segmented_customerController@getDownload');

	Route::get('segmentedCustomers/send_email', 'Segmented_customerController@send_email');

	// Route::get('particularCustomers', ['as' => 'pages.particularCustomers', 'uses' => 'Particular_customerController@index']);
	// Route::get('particularCustomers/edit/{id}', 'Particular_customerController@getCustomerInfo');
	// Route::post('particularCustomers/create', 'Particular_customerController@create');
	// Route::post('particularCustomers/edit/{id}/update', 'Particular_customerController@update');
	// Route::delete('particularCustomers/delete/{id}', 'Particular_customerController@deleteCustomerParticular');
	// Route::get('particularCustomers/filterToCSV', 'Particular_customerController@getFilteredQueryResults');
	// Route::get('particularCustomers/filterToCSV/download', 'Particular_customerController@getDownload');

	Route::get('webservice', ['as' => 'pages.webservice', 'uses' => 'Product_hermidaController@index']);
});

/* DATATABLES */
Route::group(['middleware' => 'auth'], function () {
	Route::get('datatables/customers/resale', 'Resale_customerController@getAllCustomers_Resale')->name('getAllCustomers_Resale');
	Route::get('datatables/customers/segmented', 'Segmented_customerController@getAllCustomers_Segmented')->name('getAllCustomers_Segmented');
	Route::get('datatables/customers/particular', 'Particular_customerController@getAllCustomers_Particular')->name('getAllCustomers_Particular');

	Route::get('datatables/attributes1', 'Attributes1Controller@getAllAttributes_1')->name('getAllAttributes_1');
	Route::get('datatables/attributes2', 'Attributes1Controller@getAllAttributes_2')->name('getAllAttributes_2');
	Route::get('datatables/attributes3', 'Attributes1Controller@getAllAttributes_3')->name('getAllAttributes_3');
	Route::get('datatables/attributes4', 'Attributes1Controller@getAllAttributes_4')->name('getAllAttributes_4');
	Route::get('datatables/attributes5', 'Attributes1Controller@getAllAttributes_5')->name('getAllAttributes_5');
	Route::get('datatables/attributes6', 'Attributes1Controller@getAllAttributes_6')->name('getAllAttributes_6');
	Route::get('datatables/attributes7', 'Attributes1Controller@getAllAttributes_7')->name('getAllAttributes_7');
	Route::get('datatables/attributes8', 'Attributes1Controller@getAllAttributes_8')->name('getAllAttributes_8');

	Route::get('datatables/products/hermida', 'Product_hermidaController@getAllProducts_hermida')->name('getAllProducts_hermida');
	Route::get('datatables/products/gmbh', 'Product_gmbhController@getAllProducts_gmbh')->name('getAllProducts_gmbh');
	Route::get('datatables/products/exadi', 'Product_exadiController@getAllProducts_exadi')->name('getAllProducts_exadi');

	Route::get('datatables/app/equipment_key', 'Equipment_keyController@getAllEquipment_Keys')->name('getAllEquipment_Keys');
});

/* CREATE */
Route::group(['middleware' => 'auth'], function () {
	// Route::get('/settings/attributes', 'Attributes1Controller@index')->name('settings/attributes'); // VISTA
	Route::post('/settings/attributes/createAtr1', 'Attributes1Controller@createAtr1')->name('attributes.createAtr1'); // CRIAR NOVO ATRIBUTO 1
	Route::post('/settings/attributes/createAtr2', 'Attributes1Controller@createAtr2')->name('attributes.createAtr2'); // CRIAR NOVO ATRIBUTO 1
	Route::post('/settings/attributes/createAtr3', 'Attributes1Controller@createAtr3')->name('attributes.createAtr3'); // CRIAR NOVO ATRIBUTO 1
	Route::post('/settings/attributes/createAtr4', 'Attributes1Controller@createAtr4')->name('attributes.createAtr4'); // CRIAR NOVO ATRIBUTO 1
	Route::post('/settings/attributes/createAtr5', 'Attributes1Controller@createAtr5')->name('attributes.createAtr5'); // CRIAR NOVO ATRIBUTO 1
	Route::post('/settings/attributes/createAtr6', 'Attributes1Controller@createAtr6')->name('attributes.createAtr6'); // CRIAR NOVO ATRIBUTO 1
	Route::post('/settings/attributes/createAtr7', 'Attributes1Controller@createAtr7')->name('attributes.createAtr7'); // CRIAR NOVO ATRIBUTO 1
	Route::post('/settings/attributes/createAtr8', 'Attributes1Controller@createAtr8')->name('attributes.createAtr8'); // CRIAR NOVO ATRIBUTO 1
});

/* DELETE */
Route::group(['middleware' => 'auth'], function () {
	Route::delete('/settings/attributes/deleteAtr1/{id}', 'Attributes1Controller@deleteAtr1'); // DELETE
	Route::delete('/settings/attributes/deleteAtr2/{id}', 'Attributes1Controller@deleteAtr2'); // DELETE
	Route::delete('/settings/attributes/deleteAtr3/{id}', 'Attributes1Controller@deleteAtr3'); // DELETE
	Route::delete('/settings/attributes/deleteAtr4/{id}', 'Attributes1Controller@deleteAtr4'); // DELETE
	Route::delete('/settings/attributes/deleteAtr5/{id}', 'Attributes1Controller@deleteAtr5'); // DELETE
	Route::delete('/settings/attributes/deleteAtr6/{id}', 'Attributes1Controller@deleteAtr6'); // DELETE
	Route::delete('/settings/attributes/deleteAtr7/{id}', 'Attributes1Controller@deleteAtr7'); // DELETE
	Route::delete('/settings/attributes/deleteAtr8/{id}', 'Attributes1Controller@deleteAtr8'); // DELETE
});

/* emails */
Route::group(['middleware' => 'auth'], function () {
	Route::get("/send_email/apresentacao_email/{id}", 'MailController@apresentacao_email');
});

/* WEB SERVICE */

/* ***************** API CUBIQUE *************************** */
Route::group(['middleware' => 'auth'], function () {
	/* GET ALL */
	Route::get('/webservice/all/generateCSV/', 'Api_providersController@generateCSV');
	Route::get('/webservice/all/download/', 'Api_providersController@getDownload');
	Route::get('/webservice/all/removefile/', 'Api_providersController@removeFile');

	/* HERMIDA */
	Route::get('/webservice/hermida/bulkUpdate/', 'Product_hermidaController@bulkUpdate');

	/* GMBH */
	Route::get('/webservice/gmbh/bulkUpdate/', 'Product_gmbhController@bulkUpdate');
	Route::post('/webservice/gmbh/bulkUpdate/', 'Product_gmbhController@bulkUpdate');

	/* EXADI */
	Route::get('/webservice/exadi/bulkUpdate/', 'Product_exadiController@update_price_and_stock');
});

/* test OFFICEGEST */
Route::group(['middleware' => 'auth'], function () {
	/* GET ALL */
	Route::get('officegest', [
		'as' => 'pages.OfficeGest_home',
		'uses' => 'OfficeGestController@index'
	]);

	Route::get('officegest/entities', [
		'as' => 'pages.OfficeGest_entities',
		'uses' => 'OfficeGestController@entities_view'
	]);

	Route::get('officegest/crm', [

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth

@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="#" class="simple-text logo-mini">{{ __('BD') }}</a>
            <a href="#" class="simple-text logo-normal">{{ __('CUBIQUE Solutions') }}</a>
        </div>
        {{-- <ul class="nav">
            <li @if ($pageSlug == 'dashboard') class="active " @endif>
                <a href="{{ route('home') }}">
        <i class="tim-icons icon-chart-pie-36"></i>
        <p>{{ __('Dashboard') }}</p>
        </a>
        </li>
        <li>
            <a data-toggle="collapse" href="#laravel-examples" aria-expanded="true">
                <i class="fab fa-laravel"></i>
                <span class="nav-link-text">{{ __('Laravel Examples') }}</span>
                <b class="caret mt-1"></b>
            </a>

            <div class="collapse show" id="laravel-examples">
                <ul class="nav pl-4">
                    <li @if ($pageSlug=='profile' ) class="active " @endif>
                        <a href="{{ route('profile.edit')  }}">
                            <i class="tim-icons icon-single-02"></i>
                            <p>{{ __('User Profile') }}</p>
                        </a>
                    </li>
                    <li @if ($pageSlug=='users' ) class="active " @endif>
                        <a href="{{ route('user.index')  }}">
                            <i class="tim-icons icon-bullet-list-67"></i>
                            <p>{{ __('User Management') }}</p>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li @if ($pageSlug=='icons' ) class="active " @endif>
            <a href="{{ route('pages.icons') }}">
                <i class="tim-icons icon-atom"></i>
                <p>{{ __('Icons') }}</p>
            </a>
        </li>
        <li @if ($pageSlug=='maps' ) class="active " @endif>
            <a href="{{ route('pages.maps') }}">
                <i class="tim-icons icon-pin"></i>
                <p>{{ __('Maps') }}</p>
            </a>
        </li>
        <li @if ($pageSlug=='notifications' ) class="active " @endif>
            <a href="{{ route('pages.notifications') }}">
                <i class="tim-icons icon-bell-55"></i>
                <p>{{ __('Notifications') }}</p>
            </a>
        </li>
        <li @if ($pageSlug=='tables' ) class="active " @endif>
            <a href="{{ route('pages.tables') }}">
                <i class="tim-icons icon-puzzle-10"></i>
                <p>{{ __('Table List') }}</p>
            </a>
        </li>
        <li @if ($pageSlug=='typography' ) class="active " @endif>
            <a href="{{ route('pages.typography') }}">
                <i class="tim-icons icon-align-center"></i>
                <p>{{ __('Typography') }}</p>
            </a>
        </li>
        <li @if ($pageSlug=='rtl' ) class="active " @endif>
            <a href="{{ route('pages.rtl') }}">
                <i class="tim-icons icon-world"></i>
                <p>{{ __('RTL Support') }}</p>
            </a>
        </li>
        <li class=" {{ $pageSlug == 'upgrade' ? 'active' : '' }}">
            <a href="{{ route('pages.upgrade') }}">
                <i class="tim-icons icon-spaceship"></i>
                <p>{{ __('Upgrade to PRO') }}</p>
            </a>
        </li>
        </ul> --}}



        {{-- ***************************************** --}}

        <ul class="nav">
            {{-- <li @if ($pageSlug == 'Home') class="active " @endif>
                <a href="{{ route('home') }}">
            <i class="tim-icons icon-chart-pie-36"></i>
            <p>{{ __('Dashboard') }}</p>
            </a>
            </li> --}}

            {{-- CLIENTES --}}

            {{-- <li @if ($pageSlug=='particularCustomers' ) class="active " @endif>
                <a href="{{ route('pages.particularCustomers') }}">
            <i class="fas fa-address-book"></i>
            <p>{{ __('Clientes - Particulares') }}</p>
            </a>
            </li> --}}

            <li @if ($pageSlug=='resaleCustomers' ) class="active " @endif>
                <a href="{{ route('pages.resaleCustomers') }}">
                    <i class="fas fa-address-book"></i>
                    <p>{{ __('Clientes - Revenda') }}</p>
                </a>
            </li>

            <li @if ($pageSlug=='segmentedCustomers' ) class="active " @endif>
                <a href="{{ route('pages.segmentedCustomers') }}">
                    <i class="fas fa-address-book"></i>
                    <p>{{ __('Clientes - Segmentada') }}</p>
                </a>
            </li>

            {{-- DEFINIÇÕES DE UTILIZADOR --}}
            <li>
                <a data-toggle="collapse" href="#user-management" aria-expanded="false">
                    <i class="fas fa-cogs"></i>
                    <span class="nav-link-text">{{ __('Definições de Utilizador') }}</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse" id="user-management">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug=='profile' ) class="active " @endif>
                            <a href="{{ route('profile.edit')  }}">
                                <i class="fas fa-id-card"></i>
                                <p>{{ __('Perfil') }}</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            {{-- ATRIBUTOS --}}
            <li>
                <a data-toggle="collapse" href="#attributes" aria-expanded="false">
                    <i class="fas fa-cogs"></i>
                    <span class="nav-link-text">{{ __('Definições da Página') }}</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse" id="attributes">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug=='attributes' ) class="active " @endif>
                            <a href="{{ route('pages.attributes')  }}">
                                <i class="fas fa-sliders-h"></i>
                                <p>{{ __('Gestor de Atributos') }}</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            {{-- WEBSERVICE --}}
            <li @if ($pageSlug=='webService' ) class="active " @endif>
                <a href="{{ route('pages.webservice') }}">
                    <i class="fab fa-cloudversify"></i>
                    <p>{{ __('Webservice - Fornecedores') }}</p>
                </a>
            </li>

            {{-- OfficeGest --}}
            <li @if ($pageSlug=='OfficeGest_home' ) class="active " @endif>
                <a href="{{ route('pages.OfficeGest_home') }}">
                    <i class="fab fa-cloudversify"></i>
                    <p>{{ __('OfficeGest') }}</p>
                </a>
            </li>



        </ul>



    </div>
</div>